### PR TITLE
Implemented func: Create Node

### PR DESCRIPTION
**Pull request by vitan**

### CODE REVIEW

**Comment by cmingxu** [comment]
Few questions:

1, are we use the advertise address as a docker daemon endpoint?
2, what about the first node want join into the cluster?

**Comment by vitan** [comment]
@cmingxu  This PR is trying to solve the problem: we have to add docker tcp entrypoint again, although we have give the node advertiseAddr

> 1, are we use the advertise address as a docker daemon endpoint?
Yes, It make sense

>2, what about the first node want join into the cluster?
The PR don't solve it. We need init the first manager still.

**Comment by vitan** [comment]
retest this please

**Comment by cmingxu** [comment]
@vitan I think the advertise address and docker daemon endpoint are different things, "advertise address" is a swarmkit concept for inter node connectivity while docker daemon is for API request(both tcp and unix sock are fine)

**Comment by vitan** [comment]
@cmingxu  Sure. But both the IP value of advertise addr and docker daemon endpoint are constantly same one. Please show me an negative example if possible.

**Comment by vitan** [comment]
@cmingxu  I will Merge it firstly. Please make another PR is any problem

**Pull request merged**
