### PR TITLE
Improved description when the stack not export port.

### PR DESCRIPTION
**Pull request by zhangsean**
Improved description when the stack not export port.

### CODE REVIEW

**Comment by xiaods** [comment]
@zhangsean thanks for your pr. could you please rebase the pr to single patch, it will help us understand the pr with one layer patch.
such as:
use git rebase -i HEAD~5

**Comment by zhangsean** [comment]
Sorry, I just have no idea how to git rebase. After I run 'git rebase -i HEAD~3' on my windows git directory, I choose the last three commits that I want to PR, then commit these three commits one by one, while I have nothing to push, and I got nothing change on github.com. Would you please help me?

**Comment by zhangsean** [comment]
@xiaods

**Comment by vitan** [comment]
@zhangsean  

please google the following cmd:

```
git rebase -i HEAD~15
```

**Comment by zhangsean** [comment]
rebase it.

**Pull request closed without merging**
