### PR TITLE
Fix gofmt -s to unfmt files

### PR DESCRIPTION
**Pull request by xiaods**

### CODE REVIEW

**Comment by vitan** [comment]
The change still work? really?

@cmingxu  @upccup  give a review please

**Comment by vitan** [comment]
please add unittest

**Comment by xiaods** [comment]
gofmt feature, not manual modify. so how way to add unit test?

**Comment by xiaods** [comment]
retest this please

**Comment by xiaods** [comment]
retest this please

**Comment by xiaods** [comment]
retest this please

**Comment by liuzhengbaihe** [comment]
retest this please

**Comment by liuzhengbaihe** [comment]
retest this please

**Comment by xiaods** [comment]
retest this please

**Pull request closed without merging**
