### PR TITLE
use gin SSeEvent replace sse pkg

### PR DESCRIPTION
**Pull request by upccup**

### CODE REVIEW

**Comment by upccup** [comment]
because of gin is supported hhtp response with sse, remove the 3rd pkg sse and replace by gin SSeEvent function

**Comment by cmingxu** [comment]
how about make SSE event types const, as they scatter all over the code base.

**Comment by upccup** [comment]
@cmingxu  good idea

**Comment by vitan** [comment]
LGTM

**Comment by cmingxu** [comment]
LGTM

**Pull request merged**
