### PR TITLE
Improved the style and tips for node edit dialog.

### PR DESCRIPTION
**Pull request by zhangsean**
Improved the style and tips for node edit dialog.

### CODE REVIEW

**Comment by vitan** [comment]
@merryfox  , give a review please

**Comment by vitan** [comment]
retest this please

**Comment by merryfox** [comment]
CSS +1

**Comment by vitan** [comment]
LGTM

**Comment by cmingxu** [comment]
how about add a unique css class for this specific usage instead of change it globally.

**Comment by zhangsean** [comment]
I add a new css style for it.

**Comment by cmingxu** [comment]
LGTM

**Pull request merged**
