### PR TITLE
add macos supoort for development setup

### PR DESCRIPTION
**Pull request by xiaods**
in current development, almost developer use mac as base env.
so now add support macos to setup development env with below cmd:

CRANE_ADDR=<your eth0 ip> ./bin/build-push-or-up.sh up

### CODE REVIEW

**Comment by vitan** [comment]
Add "MacOS support" to https://github.com/Dataman-Cloud/crane#os-supported

**Comment by xiaods** [comment]
please hold on, it depend on env branch feature merged before.

**Comment by xiaods** [comment]
#544 is blocking issue.

**Comment by xiaods** [comment]
close it and merge to another PR.

**Pull request closed without merging**
