### PR TITLE
enhance utils config testing and support mac devel

### PR DESCRIPTION
**Pull request by xiaods**
enhance utils config testing and support mac devel
    
    Covering:
    1. utils/config/...
    2. replace os.exit by log.Fatalf
    3. refactor GetConfig to InitConfig
    4. envfile should be load by system not app daemon. and app can handle env.
    5. finish integration test env setup
    
    Tesing:
    ```
    go test -v ./src/utils/config/...
    ```
    
    6 add macos supoort for development setup
    
    in current development, almost developer use mac as base env.
    so now add support macos to setup development env with below cmd:
    
    ```
    CRANE_IP=<your eth0 ip> ./bin/build-push-or-up.sh up
    ```

### CODE REVIEW

**Comment by xiaods** [comment]
hold on

**Comment by xiaods** [comment]
ping @douzl PTAL!

**Comment by xiaods** [comment]
hold on, i found a potential bug for env parse

**Comment by vitan** [comment]
jenkin error info

```
+ ./run.sh
[INFO] http get misc/v1/help

http: error: ConnectionError: ('Connection aborted.', BadStatusLine("''",)) while doing GET request to URL: http://localhost:5013/misc/v1/help
 [;31m ~ [FAIL] request misc/v1/help get respone status code get 0 not 200 [0m 
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
```

**Comment by xiaods** [comment]
yeah, found it.

**Comment by xiaods** [comment]
if merged this patch, only development is ok. the release phase is not confirmed and need update later.

**Pull request merged**
